DROP TABLE ORDER_DETAIL;
DROP TABLE ORDER_MASTER;
DROP TABLE TRACKING_LIST;
DROP TABLE PROMO_DETAIL;
DROP TABLE PROMO_LIST;
DROP TABLE COURSE_VIDEO;
DROP TABLE COURSE;
DROP TABLE COURSE_TYPE;
DROP TABLE COUP_CODE;

--↓↓↓↓↓↓↓↓↓↓↓↓↓↓假的↓↓↓↓↓↓↓↓↓↓↓↓↓↓
DROP TABLE TEACHER;
DROP TABLE MEMBERS;
--↑↑↑↑↑↑↑↑↑↑↑↑↑↑假的↑↑↑↑↑↑↑↑↑↑↑↑↑↑

DROP SEQUENCE SEQ_CS;
DROP SEQUENCE SEQ_CSVIDEO;
DROP SEQUENCE SEQ_COUP_CODEQ;
DROP SEQUENCE SEQ_PROM;
DROP SEQUENCE SEQ_ORDER_MASTER;
DROP SEQUENCE SEQ_CSTYPE;

--↓↓↓↓↓↓↓↓↓↓↓↓↓↓假的↓↓↓↓↓↓↓↓↓↓↓↓↓↓
DROP SEQUENCE SEQ_MEMBERS;
DROP SEQUENCE SEQ_TCHR;

CREATE TABLE MEMBERS(
	MEMNO 			VARCHAR2(8) PRIMARY KEY NOT NULL
);

CREATE TABLE TEACHER(
	TCHRNO 			VARCHAR2(8) PRIMARY KEY NOT NULL
);
--↑↑↑↑↑↑↑↑↑↑↑↑↑↑假的↑↑↑↑↑↑↑↑↑↑↑↑↑↑

CREATE TABLE COURSE_TYPE(
	CSTYPENO 		VARCHAR2(8) PRIMARY KEY NOT NULL,
	CSTYPENAME		VARCHAR2(50)	
);

CREATE TABLE COURSE(
	COURSENO		VARCHAR2(8) NOT NULL,
	CSTYPENO		VARCHAR2(8) NOT NULL,
	TCHRNO			VARCHAR2(8) NOT NULL,
	COURSENAME		VARCHAR2(50) NOT NULL,
	COURSEINFO		CLOB,
	COURSEPRICE		NUMBER(6) NOT NULL,
	TTLTIME			NUMBER(6),
	CSSTATUS		VARCHAR(20) DEFAULT '審核中' CHECK(CSSTATUS IN('審核中','上架','下架')) NOT NULL,
	CSSCORE			NUMBER(8),
	CSSCORETIMES	NUMBER(5),	
	CONSTRAINT PK_COURSE PRIMARY KEY (COURSENO),
	CONSTRAINT FK_COURSE_COURSE_TYPE FOREIGN KEY (CSTYPENO) REFERENCES COURSE_TYPE(CSTYPENO),
	CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY (TCHRNO) REFERENCES TEACHER(TCHRNO)
);

CREATE TABLE COURSE_VIDEO(
	VIDEONO			VARCHAR2(8) NOT NULL,
	COURSENO 		VARCHAR2(8) NOT NULL,
	CSSCOPE			NUMBER(3) NOT NULL,
	CHAPTERNO		NUMBER(3) NOT NULL,
	CHAPTERNAME 	VARCHAR2(50),
	CHAPTERLEN		NUMBER(4),
	VIDEO 			BLOB NOT NULL,
	CONSTRAINT PK_COURSE_VIDEO PRIMARY KEY (VIDEONO),
	CONSTRAINT FK_COURSE_VIDEO_COURSE FOREIGN KEY (COURSENO) REFERENCES COURSE(COURSENO)
);

CREATE TABLE COUP_CODE(
	COUPNO 			VARCHAR2(8) NOT NULL,
	MEMNO 			VARCHAR2(8) NOT NULL,
	COUPCODE 		VARCHAR2(10),
	DISCAMT			NUMBER(6),
	DISCSTATUS		NUMBER(1) DEFAULT 0 CHECK(DISCSTATUS IN (0, 1)),
	COUPTIME 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	COUPEXP 		DATE,
    CONSTRAINT PK_COUP_CODE PRIMARY KEY (COUPNO),
    CONSTRAINT FK_COUP_CODE_MEMBERS FOREIGN KEY (MEMNO) REFERENCES MEMBERS(MEMNO)
);

CREATE TABLE PROMO_LIST(
	PROMONO 		VARCHAR2(8) NOT NULL,
	PROMONAME 		VARCHAR2(20),
	STARTDATE 		DATE NOT NULL,
	ENDDATE 		DATE NOT NULL,
	PROMOINFO 		VARCHAR2(60),
	CONSTRAINT PK_PROMO_LIST PRIMARY KEY (PROMONO)
);

CREATE TABLE PROMO_DETAIL(
	PROMONO 		VARCHAR2(8) NOT NULL,
	CSTYPENO 		VARCHAR2(8) NOT NULL,
	PERCENTAGE 		NUMBER(3),
	CONSTRAINT PK_PROMO_DETAIL PRIMARY KEY (PROMONO, CSTYPENO),
	CONSTRAINT FK_PROMO_DETAIL_PROMO_LIST FOREIGN KEY (PROMONO) REFERENCES PROMO_LIST(PROMONO),
	CONSTRAINT FK_PROMO_DETAIL_COURSE_TYPE FOREIGN KEY (CSTYPENO) REFERENCES COURSE_TYPE(CSTYPENO)
);

CREATE TABLE ORDER_MASTER(
	ORDERNO 		VARCHAR2(8) NOT NULL,
	MEMNO 			VARCHAR2(8) NOT NULL,
	ORDERDATE		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ORDERSTATUS		VARCHAR2(20) DEFAULT '未付款' CHECK (ORDERSTATUS IN ('未付款','已付款','失效訂單','已結單')),
	ORDERAMT 		NUMBER(6),
	COUPNO 			VARCHAR2(8),
	PAYBY 			VARCHAR2(20),
	CONSTRAINT PK_ORDER_MASTER PRIMARY KEY (ORDERNO),
	CONSTRAINT FK_ORDER_MASTER_MEMBERS FOREIGN KEY (MEMNO) REFERENCES MEMBERS(MEMNO),
	CONSTRAINT FK_ORDER_MASTER_COUP_CODE FOREIGN KEY (COUPNO) REFERENCES COUP_CODE(COUPNO)
);

CREATE TABLE ORDER_DETAIL(
	ORDERNO			VARCHAR2(8) NOT NULL,
	COURSENO		VARCHAR2(8) NOT NULL,
	SELLPRICE		NUMBER(6),
	ODSTATUS 		VARCHAR2(20) DEFAULT '鑑賞期' CHECK (ODSTATUS IN ('鑑賞期','申請退款','退款完成','交易完成')),
	PROMONO			VARCHAR2(8),
	CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (ORDERNO, COURSENO),
	CONSTRAINT FK_ORDER_DETAIL_ORDER_MASTER FOREIGN KEY (ORDERNO) REFERENCES ORDER_MASTER(ORDERNO),
	CONSTRAINT FK_ORDER_DETAIL_COURSE FOREIGN KEY (COURSENO) REFERENCES COURSE(COURSENO),
	CONSTRAINT FK_ORDER_DETAIL_PROMO_LIST FOREIGN KEY (PROMONO) REFERENCES PROMO_LIST(PROMONO)
);

CREATE TABLE TRACKING_LIST(
	MEMNO 			VARCHAR2(8) NOT NULL,
	COURSENO 		VARCHAR2(8) NOT NULL,
    CONSTRAINT PK_TRACKING_LIST PRIMARY KEY (MEMNO, COURSENO)
);


--↓↓↓↓↓↓↓↓↓↓↓↓↓↓假的↓↓↓↓↓↓↓↓↓↓↓↓↓↓
CREATE SEQUENCE SEQ_MEMBERS
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_TCHR
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;
--↑↑↑↑↑↑↑↑↑↑↑↑↑↑假的↑↑↑↑↑↑↑↑↑↑↑↑↑↑


CREATE SEQUENCE SEQ_CS
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CSTYPE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CSVIDEO
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_COUP_CODE
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_PROM
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_ORDER_MASTER
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

commit;

--會員

INSERT INTO MEMBERS VALUES ('MEM' || LPAD(SEQ_MEMBERS.NEXTVAL, 4, 0));
INSERT INTO MEMBERS VALUES ('MEM' || LPAD(SEQ_MEMBERS.NEXTVAL, 4, 0));
INSERT INTO MEMBERS VALUES ('MEM' || LPAD(SEQ_MEMBERS.NEXTVAL, 4, 0));
INSERT INTO MEMBERS VALUES ('MEM' || LPAD(SEQ_MEMBERS.NEXTVAL, 4, 0));
INSERT INTO MEMBERS VALUES ('MEM' || LPAD(SEQ_MEMBERS.NEXTVAL, 4, 0));

--老師

INSERT INTO TEACHER VALUES ('TCHR' || LPAD(SEQ_TCHR.NEXTVAL, 4, 0));
INSERT INTO TEACHER VALUES ('TCHR' || LPAD(SEQ_TCHR.NEXTVAL, 4, 0));
INSERT INTO TEACHER VALUES ('TCHR' || LPAD(SEQ_TCHR.NEXTVAL, 4, 0));
INSERT INTO TEACHER VALUES ('TCHR' || LPAD(SEQ_TCHR.NEXTVAL, 4, 0));
INSERT INTO TEACHER VALUES ('TCHR' || LPAD(SEQ_TCHR.NEXTVAL, 4, 0));

--課程種類

INSERT INTO COURSE_TYPE VALUES ('TYPE' || LPAD(SEQ_CSTYPE.NEXTVAL, 4, 0),'數學');
INSERT INTO COURSE_TYPE VALUES ('TYPE' || LPAD(SEQ_CSTYPE.NEXTVAL, 4, 0),'自然');
INSERT INTO COURSE_TYPE VALUES ('TYPE' || LPAD(SEQ_CSTYPE.NEXTVAL, 4, 0),'英文');
INSERT INTO COURSE_TYPE VALUES ('TYPE' || LPAD(SEQ_CSTYPE.NEXTVAL, 4, 0),'國文');
INSERT INTO COURSE_TYPE VALUES ('TYPE' || LPAD(SEQ_CSTYPE.NEXTVAL, 4, 0),'日文');

--課程

INSERT INTO COURSE VALUES ('COUR' || LPAD(SEQ_CS.NEXTVAL, 4, 0),'TYPE0001','TCHR0001','微積分','',3000,800,'上架',800,400);
INSERT INTO COURSE VALUES ('COUR' || LPAD(SEQ_CS.NEXTVAL, 4, 0),'TYPE0002','TCHR0004','量子物理','',2500,600,'上架',600,300);
INSERT INTO COURSE VALUES ('COUR' || LPAD(SEQ_CS.NEXTVAL, 4, 0),'TYPE0001','TCHR0001','應用數學','',1300,300,'上架',400,80);
INSERT INTO COURSE VALUES ('COUR' || LPAD(SEQ_CS.NEXTVAL, 4, 0),'TYPE0003','TCHR0002','英文口說','',1000,600,'上架',300,300);
INSERT INTO COURSE VALUES ('COUR' || LPAD(SEQ_CS.NEXTVAL, 4, 0),'TYPE0004','TCHR0003','國文寫作','',600,600,'上架',400,360);

--課程影片

INSERT INTO COURSE_VIDEO VALUES ('VID' || LPAD(SEQ_COUP_CODE.NEXTVAL, 4, 0),'COUR0001', 1, 1, '微分1', 200, EMPTY_BLOB());
INSERT INTO COURSE_VIDEO VALUES ('VID' || LPAD(SEQ_COUP_CODE.NEXTVAL, 4, 0),'COUR0001', 1, 2, '微分2', 200, EMPTY_BLOB());
INSERT INTO COURSE_VIDEO VALUES ('VID' || LPAD(SEQ_COUP_CODE.NEXTVAL, 4, 0),'COUR0002', 1, 1, '古典物理簡介', 200, EMPTY_BLOB());
INSERT INTO COURSE_VIDEO VALUES ('VID' || LPAD(SEQ_COUP_CODE.NEXTVAL, 4, 0),'COUR0003', 2, 4, '微分', 150, EMPTY_BLOB());
INSERT INTO COURSE_VIDEO VALUES ('VID' || LPAD(SEQ_COUP_CODE.NEXTVAL, 4, 0),'COUR0004', 3, 5, '日常會話', 300, EMPTY_BLOB());

--折價券

INSERT INTO COUP_CODE VALUES ('COUP' || LPAD(SEQ_COUP_CODE.NEXTVAL, 4, 0),'MEM0004','XXXX-ZXCV',150,1,TO_DATE('2020-09-02','YYYY-MM-DD'),TO_DATE('2020-09-16','YYYY-MM-DD'));

--優惠活動

INSERT INTO PROMO_LIST VALUES ('PROM' || LPAD(SEQ_PROM.NEXTVAL, 4, 0),'教師節活動',TO_DATE('2020-08-30','YYYY-MM-DD'),TO_DATE('2020-09-30','YYYY-MM-DD'),'歡慶教師節');

--優惠明細

INSERT INTO PROMO_DETAIL VALUES ('PROM0001','TYPE0004',80);

--訂單主檔

INSERT INTO ORDER_MASTER VALUES ('ORD' || LPAD(SEQ_ORDER_MASTER.NEXTVAL, 4, 0),'MEM0001',TO_DATE('2020-07-05 21:00:00','YYYY-MM-DD hh24:mi:ss'),'未付款',3000,'','信用卡');
INSERT INTO ORDER_MASTER VALUES ('ORD' || LPAD(SEQ_ORDER_MASTER.NEXTVAL, 4, 0),'MEM0002',TO_DATE('2020-08-02','YYYY-MM-DD'),'失效訂單',2500,'','信用卡');
INSERT INTO ORDER_MASTER VALUES ('ORD' || LPAD(SEQ_ORDER_MASTER.NEXTVAL, 4, 0),'MEM0003',TO_DATE('2020-09-12','YYYY-MM-DD'),'未付款',2800,'','信用卡');
INSERT INTO ORDER_MASTER VALUES ('ORD' || LPAD(SEQ_ORDER_MASTER.NEXTVAL, 4, 0),'MEM0001',TO_DATE('2020-09-21','YYYY-MM-DD'),'未付款',2800,'','信用卡');
INSERT INTO ORDER_MASTER VALUES ('ORD' || LPAD(SEQ_ORDER_MASTER.NEXTVAL, 4, 0),'MEM0004',CURRENT_TIMESTAMP,'未付款',2800,'','信用卡');

--訂單明細

INSERT INTO ORDER_DETAIL VALUES ('ORD0001','COUR0001',3000,'鑑賞期','');
INSERT INTO ORDER_DETAIL VALUES ('ORD0001','COUR0003',1300,'鑑賞期','');
INSERT INTO ORDER_DETAIL VALUES ('ORD0002','COUR0001',3000,'鑑賞期','');
INSERT INTO ORDER_DETAIL VALUES ('ORD0003','COUR0002',2500,'鑑賞期','');
INSERT INTO ORDER_DETAIL VALUES ('ORD0004','COUR0004',1000,'鑑賞期','');
INSERT INTO ORDER_DETAIL VALUES ('ORD0005','COUR0005',600,'鑑賞期','');

--追蹤清單

INSERT INTO TRACKING_LIST VALUES ('MEM0004','COUR0001');

commit;